techpack: camera: actuator: fix a compile error
This is due to LOS QCOM sm8250 repo having an extra commit not present on
Motorola caprip's kernel source code.

../../../../../../kernel/motorola/sm6115/techpack/camera/drivers/cam_sensor_module/cam_actuator/mot_actuator.c:304:57: error: too few arguments to function call, expected 3, have 2
        ret = camera_io_dev_write(io_master_info, write_setting);
              ~~~~~~~~~~~~~~~~~~~                              ^
../../../../../../kernel/motorola/sm6115/techpack/camera/drivers/cam_sensor_module/cam_sensor_io/cam_sensor_io.h:81:9: note: 'camera_io_dev_write' declared here
int32_t camera_io_dev_write(struct camera_io_master *io_master_info,
        ^
1 error generated.

Change-Id: Ie7cec12dcd40d97876c287046655fc236c44518d